name: Publish to Qiita
on:
  push:
    branches: [ main ]
    paths: [ 'articles/**' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Qiita CLI
        run: npm install -g @qiita/qiita-cli

      - name: Login and Publish
        env:
          QIITA_KEY: ${{ secrets.QIITA_KEY }}
        run: |
          # PCで成功したのと同じ「login」コマンドで設定を自動生成させます
          qiita login --token "$QIITA_KEY"
          qiita publish --all